### ISSUE TITLE
Stable is outdated

### ISSUE THREAD

**Issue by zacuke** [numerai/numerai-predict#48]
The readme indicates to use this command, but stable pulls an old copy still referencing the v4.3 data:
`docker run -i --rm -v "$PWD:$PWD" ghcr.io/numerai/numerai_predict_py_3_10:stable --model $PWD/model.pkl`

I had to change stable to latest to get the master branch:
`docker run -i --rm -v "$PWD:$PWD" ghcr.io/numerai/numerai_predict_py_3_10:latest --model $PWD/model.pkl`

**Comment by ndharasz** [comment]
sorry about this, just merged master into stable:
https://github.com/numerai/numerai-predict/commit/d31dcbd64e8a9535889ba34f4a64e9a655baba3e

Will be deployed soon.
